name = "HankNN"
uuid = "e7b8c8f0-8c8e-4b8e-8c8e-8c8e8c8e8c8e"
version = "0.1.0"
authors = ["Boston College PhD Student"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Distributions = "0.25"
JLD2 = "0.6.3"
Lux = "1.0"
Optimisers = "0.4"
Plots = "1.40"
ProgressMeter = "1.10"
StatsPlots = "0.15"
Zygote = "0.6"
julia = "1.10"
